services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_LaboDino
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./database/script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./database/triggers.sql:/docker-entrypoint-initdb.d/triggers.sql
      - ./database/populate.sql:/docker-entrypoint-initdb.d/populate.sql
    networks:
      - mariadb_network

volumes:
  mariadb_data:

networks:
  mariadb_network:
    name: LaboDino

# Pour lancer : `docker compose up -d` dans le dossier
# docker run -it --network LaboDino --rm mysql:latest mysql -h mariadb_LaboDino -u root -p